### ISSUE TITLE
Contour plot problem with arrays with nan values

### ISSUE THREAD

**Issue by jonathanlintott** [enthought/chaco#310]
There seems to be an issue when using the contour plot on an array with nan values (numpy.nan). Rather than terminating the contours at the edges of a nan value it forces the contours into closed loops, often with quite erroneous results. Below is an example shown with a data set that is undefined around all edges and has a non-rectangular shape.

```
from traits.api import HasStrictTraits, Instance
from traitsui.api import View, UItem
from chaco.api import ArrayPlotData, Plot
from enable.api import ComponentEditor
import numpy as np


class ImgPlot(HasStrictTraits):
    plot = Instance(Plot)

    traits_view = View(
        UItem('plot', editor=ComponentEditor(size=(900,800))),
        resizable=True
    )

    def __init__(self, data_array, xbounds, ybounds):
        super(ImgPlot, self).__init__()

        # Define plot data and plot instance
        plot_data = ArrayPlotData(z=data_array)
        plot = Plot(plot_data)

        # Make image plot
        plot.img_plot('z', name='img_plot', hide_grids=False, xbounds=xbounds, ybounds=ybounds)

        # Make contour plot
        plot.contour_plot('z', type='line', name='con_plot', hide_grids=False, 
                            xbounds=xbounds, ybounds=ybounds, levels=20)
        self.plot = plot
```

![picture](https://cloud.githubusercontent.com/assets/18678825/18355045/d5060f1e-75df-11e6-9b5d-198c28b4e06b.png)

Unfortunately the plotting methods can't handle numpy masked arrays either.

**Comment by jwiggins** [comment]
Just to add some color for anyone who takes a look at this: Chaco might be doing the right thing here. There's a chance that this bug is deep down in Kiva.

Those spurious straight lines are what you get when you tell AGG to close a path.

**Comment by corranwebster** [comment]
Very quick look over the code, and it looks like that although the contour code can accept a mask as an argument, the contour line plot isn't passing one in when it calls.  Compare the call at https://github.com/enthought/chaco/blob/master/chaco/contour_line_plot.py#L123 with the signature at https://github.com/enthought/chaco/blob/master/chaco/contour/cntr.c#L1555.

I doubt that AGG is at fault, since as far as I can see the line contour code doesn't do any calls to close the paths.

Fix is probably an enhancement to either accept an explicit mask array, or construct one as needed using `isfinite()` or the mask of a masked array.

**Comment by corranwebster** [comment]
@jonathanlintott if you are feeling adventurous and are comfortable with checking out and working with code from a branch in GitHub, the branch from #326 should hopefully fix your problem, and it would be nice to have confirmation that it does so.
