### ISSUE TITLE
Python 3 compatibility fixes

### ISSUE THREAD

**Issue by jdeschenes** [enthought/chaco#368]
Hello,

I am not sure who I can contact for this particular issue. 

I had several issues when trying to create an application using chaco on python 3. One of the recurring issues was the 2to3 tools getting the conversion subtly wrong. I decided to create branches for different enthought repositories:

* enable
* traits
* traitsui
* chaco
* pyface

I went over the code and ensured that there isn't a need to use the 2to3 tools and replaced it with the usage of the "six" library. I am assuming compatibility with python 2.7 and python 3+. I would very much like for you to have these changes. Is there any interest on your side to have these modifications?

In the event that you are:

1. How can I provide you with the pull requests(or one?) per repository to maximize the chances of it being accepted?

Thank you for your time.

**Comment by jvkersch** [comment]
@jdeschenes I'm also not a big fan of 2to3, and I think not a lot of people here are, so this sounds really cool :)

How extensive are the changes that you needed to make to switch to six? If you feel the changes are mostly a question of routine translation, then I'd open PRs against each of the repos straightaway, since it sounds like you have the code ready. If the code is not straightforward (very many changes, with things that are not obvious, etc) then I would recommend having one PR at a time open, starting with the repo that's easiest to fix, and working up from there.

Lastly, there is now a google mailing list for ETS-related development: https://groups.google.com/forum/#!forum/ets-users It was created last weekend so it's empty still, but if you post there you'd be sure to get the attention of the maintainers of the other repos, too.

**Comment by jwiggins** [comment]
I started to look into this with enable, but stopped after going too far. I'm looking forward to seeing this.

**Comment by jdeschenes** [comment]
I submitted a [PR on traits](https://github.com/enthought/traits/pull/374). I think this was the easiest to modify because of its extensive coverage.

**Comment by jwiggins** [comment]
Yeah, enable has poor test coverage and some of the kiva backends probably need to be put out to pasture. Here is probably not the place to discuss that.

I also found the process to be fairly mechanical (if tedious), but of course the devil is in the details.

**Comment by rahulporuri** [comment]
Closing this issue as all of the relevant packages now work on Python 3 - `enable`, `traits`, `traitsui`, `chaco`, `pyface`. We'll create separate issues/PRs when we find specific bugs.
