### ISSUE TITLE
BUG: Multiple Import Errors 

### ISSUE THREAD

**Issue by skailasa** [enthought/chaco#455]
**Problem Description**
Failure to Import `chaco.contour.contour`
Failure to Import `mock` (python 3 incompatible)

**Reproduction Steps:**

[Steps to reproduce issue here.]

```python
# Code to reproduce issue here
python -m unittest
```

**OS, Python version:** [Enter OS name and Python version]
MacOS 10.14.5, Py 3.60

**Comment by mdickinson** [comment]
We looked at this this morning; the `chaco.contour.contour` import failure was due to not building the C extensions contained in the package. The `mock` import failure is easily fixed by installing `mock` (which is required by the test suite, but correctly isn't listed as a runtime dependency).

The real bug here is a lack of developer documentation. :-) (It would also be nice to move to using the std. library `mock` on Python 3.)
