### ISSUE TITLE
Consolidate overlays into "chaco.overlays"?

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#699]
https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/axis.py#L54

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/colormapped_selection_overlay.py#L16

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/grid.py#L82

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/lasso_overlay.py#L15

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/legend.py#L79

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/plot_label.py#L15

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/scatter_inspector_overlay.py#L14

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/text_box_overlay.py#L15

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/tooltip.py#L20

Q. What about layers?

https://github.com/enthought/chaco/blob/4b3747d407527dde50af6214cad1e6cc2eb6f7b0/chaco/layers/status_layer.py#L11

**Comment by corranwebster** [comment]
Axes and grids are a little trickier, since they have a lot of machinery behind them, so you'd either want them to be separate, or to possibly bring in all the scale and tick generation code as well.

Layers probably should go in overlays as well - I think they may have been separated out before there was an overlays directory, but they are just a special case of overlays.
