### ISSUE TITLE
Remove "PopupablePlot"

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#713]
`PopupablePlot` was introduced in the commit https://github.com/enthought/chaco/commit/4af154cec6f678862ba7e695ae62d681312b50e8#diff-c93657842da48caff25acdb9de9f919f9c04b5301d0fafc28598c9fdeee829f8 but it is not clear why it exists or who uses it.

**Comment by rahulporuri** [comment]
I don't find any users of this class on GitHub - https://github.com/enthought/chaco/search?q=PopupablePlot+extension%3Apy

**Comment by rahulporuri** [comment]
I even dug around to find the commits before and after the commit that introduced this into the codebase - which doesn't help. Ref https://github.com/enthought/chaco/commits/3.0.0?after=57f3b83331c065c0d6f3d30234ababfbc461353e+139&branch=3.0.0

**Comment by corranwebster** [comment]
The design is intended to create a dialog window containing pre-specified plots from a given dataset - you give it a list of plot types and data that you want plotted and it populates.  The design is odd, since it really wants to be a Tool not a Plot.

It is using old constructs, and I have never seen it used.

It can be removed.
